server:
  port: 8085
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mohirdevdemo2
    username: postgres
    password: 2611
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
